### ISSUE TITLE
Изменить REST API PostLikeRestController

### ISSUE THREAD

**Issue by kaitanovwork** [zhassulan-team/social-network-backend-like-service#38]
1. Изменить **PostLikeRestController::addPostLike**
1.1 Возвращать `ResponseEntity<Void>`

2. Изменить **PostLikeRestController::updatePostLike**
2.1 Возвращать `ResponseEntity<Void>`

3. Покрыть тестами **PostLikeRestController**

**Comment by VirKato-dev** [comment]
Реализовано:
1. Изменить PostLikeRestController::addPostLike (Возвращать ResponseEntity<Void>)
2. Изменить PostLikeRestController::updatePostLike (Возвращать ResponseEntity<Void>)

Требуется:
1. Покрыть тестами PostLikeRestController
